// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AmazonOpenSearchServerlessS3BackupMode string

const (
	AmazonOpenSearchServerlessS3BackupMode_AllDocuments        AmazonOpenSearchServerlessS3BackupMode = "AllDocuments"
	AmazonOpenSearchServerlessS3BackupMode_FailedDocumentsOnly AmazonOpenSearchServerlessS3BackupMode = "FailedDocumentsOnly"
)

type AmazonopensearchserviceIndexRotationPeriod string

const (
	AmazonopensearchserviceIndexRotationPeriod_NoRotation AmazonopensearchserviceIndexRotationPeriod = "NoRotation"
	AmazonopensearchserviceIndexRotationPeriod_OneDay     AmazonopensearchserviceIndexRotationPeriod = "OneDay"
	AmazonopensearchserviceIndexRotationPeriod_OneHour    AmazonopensearchserviceIndexRotationPeriod = "OneHour"
	AmazonopensearchserviceIndexRotationPeriod_OneMonth   AmazonopensearchserviceIndexRotationPeriod = "OneMonth"
	AmazonopensearchserviceIndexRotationPeriod_OneWeek    AmazonopensearchserviceIndexRotationPeriod = "OneWeek"
)

type AmazonopensearchserviceS3BackupMode string

const (
	AmazonopensearchserviceS3BackupMode_AllDocuments        AmazonopensearchserviceS3BackupMode = "AllDocuments"
	AmazonopensearchserviceS3BackupMode_FailedDocumentsOnly AmazonopensearchserviceS3BackupMode = "FailedDocumentsOnly"
)

type CompressionFormat string

const (
	CompressionFormat_GZIP          CompressionFormat = "GZIP"
	CompressionFormat_HADOOP_SNAPPY CompressionFormat = "HADOOP_SNAPPY"
	CompressionFormat_Snappy        CompressionFormat = "Snappy"
	CompressionFormat_UNCOMPRESSED  CompressionFormat = "UNCOMPRESSED"
	CompressionFormat_ZIP           CompressionFormat = "ZIP"
)

type Connectivity string

const (
	Connectivity_PRIVATE Connectivity = "PRIVATE"
	Connectivity_PUBLIC  Connectivity = "PUBLIC"
)

type ContentEncoding string

const (
	ContentEncoding_GZIP ContentEncoding = "GZIP"
	ContentEncoding_NONE ContentEncoding = "NONE"
)

type DatabaseType string

const (
	DatabaseType_MySQL      DatabaseType = "MySQL"
	DatabaseType_PostgreSQL DatabaseType = "PostgreSQL"
)

type DefaultDocumentIDFormat string

const (
	DefaultDocumentIDFormat_FIREHOSE_DEFAULT DefaultDocumentIDFormat = "FIREHOSE_DEFAULT"
	DefaultDocumentIDFormat_NO_DOCUMENT_ID   DefaultDocumentIDFormat = "NO_DOCUMENT_ID"
)

type DeliveryStreamEncryptionStatus string

const (
	DeliveryStreamEncryptionStatus_DISABLED         DeliveryStreamEncryptionStatus = "DISABLED"
	DeliveryStreamEncryptionStatus_DISABLING        DeliveryStreamEncryptionStatus = "DISABLING"
	DeliveryStreamEncryptionStatus_DISABLING_FAILED DeliveryStreamEncryptionStatus = "DISABLING_FAILED"
	DeliveryStreamEncryptionStatus_ENABLED          DeliveryStreamEncryptionStatus = "ENABLED"
	DeliveryStreamEncryptionStatus_ENABLING         DeliveryStreamEncryptionStatus = "ENABLING"
	DeliveryStreamEncryptionStatus_ENABLING_FAILED  DeliveryStreamEncryptionStatus = "ENABLING_FAILED"
)

type DeliveryStreamFailureType string

const (
	DeliveryStreamFailureType_CREATE_ENI_FAILED                            DeliveryStreamFailureType = "CREATE_ENI_FAILED"
	DeliveryStreamFailureType_CREATE_KMS_GRANT_FAILED                      DeliveryStreamFailureType = "CREATE_KMS_GRANT_FAILED"
	DeliveryStreamFailureType_DELETE_ENI_FAILED                            DeliveryStreamFailureType = "DELETE_ENI_FAILED"
	DeliveryStreamFailureType_DISABLED_KMS_KEY                             DeliveryStreamFailureType = "DISABLED_KMS_KEY"
	DeliveryStreamFailureType_ENI_ACCESS_DENIED                            DeliveryStreamFailureType = "ENI_ACCESS_DENIED"
	DeliveryStreamFailureType_INVALID_KMS_KEY                              DeliveryStreamFailureType = "INVALID_KMS_KEY"
	DeliveryStreamFailureType_KMS_ACCESS_DENIED                            DeliveryStreamFailureType = "KMS_ACCESS_DENIED"
	DeliveryStreamFailureType_KMS_KEY_NOT_FOUND                            DeliveryStreamFailureType = "KMS_KEY_NOT_FOUND"
	DeliveryStreamFailureType_KMS_OPT_IN_REQUIRED                          DeliveryStreamFailureType = "KMS_OPT_IN_REQUIRED"
	DeliveryStreamFailureType_RETIRE_KMS_GRANT_FAILED                      DeliveryStreamFailureType = "RETIRE_KMS_GRANT_FAILED"
	DeliveryStreamFailureType_SECURITY_GROUP_ACCESS_DENIED                 DeliveryStreamFailureType = "SECURITY_GROUP_ACCESS_DENIED"
	DeliveryStreamFailureType_SECURITY_GROUP_NOT_FOUND                     DeliveryStreamFailureType = "SECURITY_GROUP_NOT_FOUND"
	DeliveryStreamFailureType_SUBNET_ACCESS_DENIED                         DeliveryStreamFailureType = "SUBNET_ACCESS_DENIED"
	DeliveryStreamFailureType_SUBNET_NOT_FOUND                             DeliveryStreamFailureType = "SUBNET_NOT_FOUND"
	DeliveryStreamFailureType_UNKNOWN_ERROR                                DeliveryStreamFailureType = "UNKNOWN_ERROR"
	DeliveryStreamFailureType_VPC_ENDPOINT_SERVICE_NAME_NOT_FOUND          DeliveryStreamFailureType = "VPC_ENDPOINT_SERVICE_NAME_NOT_FOUND"
	DeliveryStreamFailureType_VPC_INTERFACE_ENDPOINT_SERVICE_ACCESS_DENIED DeliveryStreamFailureType = "VPC_INTERFACE_ENDPOINT_SERVICE_ACCESS_DENIED"
)

type DeliveryStreamStatus string

const (
	DeliveryStreamStatus_ACTIVE          DeliveryStreamStatus = "ACTIVE"
	DeliveryStreamStatus_CREATING        DeliveryStreamStatus = "CREATING"
	DeliveryStreamStatus_CREATING_FAILED DeliveryStreamStatus = "CREATING_FAILED"
	DeliveryStreamStatus_DELETING        DeliveryStreamStatus = "DELETING"
	DeliveryStreamStatus_DELETING_FAILED DeliveryStreamStatus = "DELETING_FAILED"
)

type DeliveryStreamType string

const (
	DeliveryStreamType_DatabaseAsSource      DeliveryStreamType = "DatabaseAsSource"
	DeliveryStreamType_DirectPut             DeliveryStreamType = "DirectPut"
	DeliveryStreamType_KinesisStreamAsSource DeliveryStreamType = "KinesisStreamAsSource"
	DeliveryStreamType_MSKAsSource           DeliveryStreamType = "MSKAsSource"
)

type ElasticsearchIndexRotationPeriod string

const (
	ElasticsearchIndexRotationPeriod_NoRotation ElasticsearchIndexRotationPeriod = "NoRotation"
	ElasticsearchIndexRotationPeriod_OneDay     ElasticsearchIndexRotationPeriod = "OneDay"
	ElasticsearchIndexRotationPeriod_OneHour    ElasticsearchIndexRotationPeriod = "OneHour"
	ElasticsearchIndexRotationPeriod_OneMonth   ElasticsearchIndexRotationPeriod = "OneMonth"
	ElasticsearchIndexRotationPeriod_OneWeek    ElasticsearchIndexRotationPeriod = "OneWeek"
)

type ElasticsearchS3BackupMode string

const (
	ElasticsearchS3BackupMode_AllDocuments        ElasticsearchS3BackupMode = "AllDocuments"
	ElasticsearchS3BackupMode_FailedDocumentsOnly ElasticsearchS3BackupMode = "FailedDocumentsOnly"
)

type HECEndpointType string

const (
	HECEndpointType_Event HECEndpointType = "Event"
	HECEndpointType_Raw   HECEndpointType = "Raw"
)

type HTTPEndpointS3BackupMode string

const (
	HTTPEndpointS3BackupMode_AllData        HTTPEndpointS3BackupMode = "AllData"
	HTTPEndpointS3BackupMode_FailedDataOnly HTTPEndpointS3BackupMode = "FailedDataOnly"
)

type IcebergS3BackupMode string

const (
	IcebergS3BackupMode_AllData        IcebergS3BackupMode = "AllData"
	IcebergS3BackupMode_FailedDataOnly IcebergS3BackupMode = "FailedDataOnly"
)

type KeyType string

const (
	KeyType_AWS_OWNED_CMK        KeyType = "AWS_OWNED_CMK"
	KeyType_CUSTOMER_MANAGED_CMK KeyType = "CUSTOMER_MANAGED_CMK"
)

type NoEncryptionConfig string

const (
	NoEncryptionConfig_NoEncryption NoEncryptionConfig = "NoEncryption"
)

type OrcCompression string

const (
	OrcCompression_NONE   OrcCompression = "NONE"
	OrcCompression_SNAPPY OrcCompression = "SNAPPY"
	OrcCompression_ZLIB   OrcCompression = "ZLIB"
)

type OrcFormatVersion string

const (
	OrcFormatVersion_V0_11 OrcFormatVersion = "V0_11"
	OrcFormatVersion_V0_12 OrcFormatVersion = "V0_12"
)

type ParquetCompression string

const (
	ParquetCompression_GZIP         ParquetCompression = "GZIP"
	ParquetCompression_SNAPPY       ParquetCompression = "SNAPPY"
	ParquetCompression_UNCOMPRESSED ParquetCompression = "UNCOMPRESSED"
)

type ParquetWriterVersion string

const (
	ParquetWriterVersion_V1 ParquetWriterVersion = "V1"
	ParquetWriterVersion_V2 ParquetWriterVersion = "V2"
)

type ProcessorParameterName string

const (
	ProcessorParameterName_BufferIntervalInSeconds ProcessorParameterName = "BufferIntervalInSeconds"
	ProcessorParameterName_BufferSizeInMBs         ProcessorParameterName = "BufferSizeInMBs"
	ProcessorParameterName_CompressionFormat       ProcessorParameterName = "CompressionFormat"
	ProcessorParameterName_DataMessageExtraction   ProcessorParameterName = "DataMessageExtraction"
	ProcessorParameterName_Delimiter               ProcessorParameterName = "Delimiter"
	ProcessorParameterName_JsonParsingEngine       ProcessorParameterName = "JsonParsingEngine"
	ProcessorParameterName_LambdaArn               ProcessorParameterName = "LambdaArn"
	ProcessorParameterName_MetadataExtractionQuery ProcessorParameterName = "MetadataExtractionQuery"
	ProcessorParameterName_NumberOfRetries         ProcessorParameterName = "NumberOfRetries"
	ProcessorParameterName_RoleArn                 ProcessorParameterName = "RoleArn"
	ProcessorParameterName_SubRecordType           ProcessorParameterName = "SubRecordType"
)

type ProcessorType string

const (
	ProcessorType_AppendDelimiterToRecord ProcessorType = "AppendDelimiterToRecord"
	ProcessorType_CloudWatchLogProcessing ProcessorType = "CloudWatchLogProcessing"
	ProcessorType_Decompression           ProcessorType = "Decompression"
	ProcessorType_Lambda                  ProcessorType = "Lambda"
	ProcessorType_MetadataExtraction      ProcessorType = "MetadataExtraction"
	ProcessorType_RecordDeAggregation     ProcessorType = "RecordDeAggregation"
)

type RedshiftS3BackupMode string

const (
	RedshiftS3BackupMode_Disabled RedshiftS3BackupMode = "Disabled"
	RedshiftS3BackupMode_Enabled  RedshiftS3BackupMode = "Enabled"
)

type S3BackupMode string

const (
	S3BackupMode_Disabled S3BackupMode = "Disabled"
	S3BackupMode_Enabled  S3BackupMode = "Enabled"
)

type SSLMode string

const (
	SSLMode_Disabled SSLMode = "Disabled"
	SSLMode_Enabled  SSLMode = "Enabled"
)

type SnapshotRequestedBy string

const (
	SnapshotRequestedBy_FIREHOSE SnapshotRequestedBy = "FIREHOSE"
	SnapshotRequestedBy_USER     SnapshotRequestedBy = "USER"
)

type SnapshotStatus string

const (
	SnapshotStatus_COMPLETE    SnapshotStatus = "COMPLETE"
	SnapshotStatus_IN_PROGRESS SnapshotStatus = "IN_PROGRESS"
	SnapshotStatus_SUSPENDED   SnapshotStatus = "SUSPENDED"
)

type SnowflakeDataLoadingOption string

const (
	SnowflakeDataLoadingOption_JSON_MAPPING                         SnowflakeDataLoadingOption = "JSON_MAPPING"
	SnowflakeDataLoadingOption_VARIANT_CONTENT_AND_METADATA_MAPPING SnowflakeDataLoadingOption = "VARIANT_CONTENT_AND_METADATA_MAPPING"
	SnowflakeDataLoadingOption_VARIANT_CONTENT_MAPPING              SnowflakeDataLoadingOption = "VARIANT_CONTENT_MAPPING"
)

type SnowflakeS3BackupMode string

const (
	SnowflakeS3BackupMode_AllData        SnowflakeS3BackupMode = "AllData"
	SnowflakeS3BackupMode_FailedDataOnly SnowflakeS3BackupMode = "FailedDataOnly"
)

type SplunkS3BackupMode string

const (
	SplunkS3BackupMode_AllEvents        SplunkS3BackupMode = "AllEvents"
	SplunkS3BackupMode_FailedEventsOnly SplunkS3BackupMode = "FailedEventsOnly"
)
